### ISSUE TITLE
Support camel case

### ISSUE THREAD

**Issue by Emielvanbetsbrugge** [kristerkari/react-native-postcss-transformer#2]
Hey man, thanks for making these transformers, it has been really useful!

I was wondering, are you planning on having camel case support for this? I've seen that your css-to-react-native-transformer supports it. I'd love to see this happening for this module too.

Is this something that might be coming soon? I'm also definitely down to just fork and contribute!

Cheers

**Comment by kristerkari** [comment]
Thanks @Emielvanbetsbrugge! 

Using camel case in class names should work out of the box, so it sounds a bit surprising to me that it does not work for you. Could you provide a bit more info about the exact problem that you are having?

**Comment by Emielvanbetsbrugge** [comment]
Yeah sorry a bit of a weird explanation. What I'm looking for is a way of writing ``.this-class {`` or ``.this--header {`` in css and being able to use ``styles.thisClass`` in the result. So that we can still use BEM. It's a bit cleaner in production in our team here. 

What's your opinion on this? :) 

Thanks for your time!

**Comment by kristerkari** [comment]
Ah, I see what you mean now. 

The thing is that the classnames appear in JavaScript the way that you have written them in CSS, and that is by design. There are however options on how you access them in your JavaScript!

**So if, you want to use the `style` property or the [className](https://github.com/kristerkari/babel-plugin-react-native-classname-to-style) property:**

```css
.thisClass {
  color: black;
}
```

```jsx
<MyElement className={styles.thisClass} />
```

and 

```css
.this-class {
  color: black;
}
```

```jsx
<MyElement className={styles["this-class"]} />
```

**You can also use the [styleName](https://github.com/kristerkari/babel-plugin-react-native-stylename-to-style) property and use the classnames as strings:**

```css
.thisClass {
  color: black;
}
```

```jsx
<MyElement styleName="thisClass" />
```

and

```css
.this-class {
  color: black;
}
```

```jsx
<MyElement styleName="this-class" />
```

So the `className` syntax still allows you to access class names with dashes or underscores, but if you want to have the class names as strings, you can install the babel plugin and switch to using `styleName` property.

* https://github.com/kristerkari/babel-plugin-react-native-classname-to-style
* https://github.com/kristerkari/babel-plugin-react-native-stylename-to-style

I hope that this helps with your issue. :)

**Comment by Emielvanbetsbrugge** [comment]
Hmm yeah I see, thanks for the nice explanation! 👍

**Comment by kristerkari** [comment]
No worries, just ask if you run into any issues 👍
