### ISSUE TITLE
Failed to parse declaration "boxShadow ..."

### ISSUE THREAD

**Issue by pqt** [kristerkari/react-native-postcss-transformer#3]
I realize that `box-shadow` isn't supported in React Native. However I _lot_ of design system uses it. Is there a way I can have this property ignored? I have no problem implementing the [shadow props](https://facebook.github.io/react-native/docs/shadow-props) but currently can't even import the stylesheets because it fails with the boxShadow failing.

**Comment by kristerkari** [comment]
Hi @pqt!

`box-shadow` is supported by the CSS parser that is used by the transformer, so it should work.

Would you happen to have a code example of the issue that you are having?

**Comment by kristerkari** [comment]
Oh yeah now I understood your problem.

In the parser that is used for React Native, `box-shadow` does not take the `spread-radius` parameter, and that is why you are getting the error:
https://github.com/styled-components/css-to-react-native/blob/master/src/__tests__/boxShadow.js

**Comment by pqt** [comment]
Hey @kristerkari I kind of abuse the `box-shadow` property on my design system, so I wouldn't believe it would be able to convert it to a react-native friendly version.

[Here's an example of the shadows used throughout](https://github.com/pqt/ui/blob/master/modules/ui/src/utils/Variables.css).

**Comment by kristerkari** [comment]
oh I see. As you wrote, that won't work because React Native can't handle the `spread-radius` parameter or multiple box shadows separated by comma.

What I would recommend to do would be to load a different style file(s) for native where you don't have those variables defined.

You can do that using this Babel plugin:
https://github.com/kristerkari/babel-plugin-react-native-platform-specific-extensions

**Comment by pqt** [comment]
Oh! Cheers. This is definitely enough to solve the problem in this case. Thank you very much!
